# Generated by Django 4.2.1 on 2023-05-11 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrotation',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='taskrotation',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
