# Generated by Django 4.2.1 on 2023-05-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskrotation_tasks_alter_taskrotation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrotation',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.task'),
        ),
    ]
